language: objective-c
env:
  matrix:
  - MONO_VERSION="3.4.0"
  global:
  - REPO="https://github.com/flickr-downloadr/flickr-downloadr.github.io.git"
  - secure: BlgjX4Szqo5ueziHsLep9wrURiWLpth1vsYO75YE63jWrS9pPnUdFJiB3wHWZf0D0a1R2EWAz9aRTOAFyHPLRmK7uQL8acmRoebpLYkHCdGaYsbWqaIvFLhYd4yqDCSV1JbU1DVJxLGXCZ1S39UNtznci+MuyFjy/RreciCWhQ8=
  - secure: aNNjDler0hHuiPXBSNptNRAtH9ZFGZxiah8Oik3HKp4lVJm5eYZS4ZYXZPyy5HdBoDwQvzFuwQ5b9yJJ8AJmDApuQ/f3sZB7JarN+J2abVFEr8DQWRIIoh08MA3t68od0UYXr2rTQ0DnCdRHa0WfZHUf1RUQr16NzDwzn1b4SUc=
before_install:
- wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
- sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
- wget "http://installbuilder.bitrock.com/installbuilder-enterprise-8.6.0-osx-installer.dmg"
- hdiutil mount installbuilder-enterprise-8.6.0-osx-installer.dmg
- sudo '/Volumes/InstallBuilder Multiplatform Enterprise 8.6.0/installbuilder-enterprise-8.6.0-osx-installer.app/Contents/MacOS/installbuilder.sh' --mode unattended --unattendedmodeui none
script:
- cd build-tools
- ./go.sh travis Release
after_success:
- git config --global user.name "flickr-downloadr CI"
- git config --global user.email "contact.us@flickrdownloadr.org"
- BUILDNUMBER=$(head -n 1 build.number)
- cd ../..
- git clone -b master $REPO
- cd flickr-downloadr.github.io
- git config credential.helper "store --file=.git/fd-credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/fd-credentials
- git config push.default tracking
- git checkout -b deploy-v${BUILDNUMBER}
- cp -r ../flickr-downloadr-gtk/dist/* ./installer
- cp ../flickr-downloadr-gtk/build-tools/build.number .
- git add -f .
- git commit -m "created release v${BUILDNUMBER}"
- git push -f -u origin deploy-v${BUILDNUMBER}
