language: objective-c
env:
  matrix:
  - MONO_VERSION="3.4.0"
  global:
    - REPO="git@github.com:flickr-downloadr/flickr-downloadr.github.io"
    - secure: "BlgjX4Szqo5ueziHsLep9wrURiWLpth1vsYO75YE63jWrS9pPnUdFJiB3wHWZf0D0a1R2EWAz9aRTOAFyHPLRmK7uQL8acmRoebpLYkHCdGaYsbWqaIvFLhYd4yqDCSV1JbU1DVJxLGXCZ1S39UNtznci+MuyFjy/RreciCWhQ8="
    - secure: "UvTnry97E3fSo7Km844pMgZQbGRAmro572o51F8Gt8lYF96api9ptf6pVEyY+syjKPXX46bVbjQBPDUlaI0DV6bWV6TlO9FQKtYpTmW8e7gc6AtKYTCQs2f2YvRWb5wAJ59B6aWAVa4h4ecAmGCCV7t7jJ7TIFaeDBM/AyceHrM="
    - secure: "jEcw0ymcEr59mT1jM+KYeWeSrc5SGVWWYOz9peey1QBMcVekWeyqfP1jP9RvG0djNtggqoYaH5ChfoDBFcznt5/rmCzprASBk8xG074Au8tJkQWrdfJYsNXzzXkmWbbJ8HpRAsfESv3KpN7FGbPv/Z8jz+wtTPlommvdD62A7Ec="
    - secure: "bna9+pJFfH9aa9XRCi/fm5FrLs/Gey8TZWX2BeOuQ6/HsMFEZjBGWJlA1FMLnQVmkkbz6jFlLMuPY64HYyDF1HRpVdK+l8a7BlPvj9d00VnuOE1SEm9CMcWYu3mVorvW8uudOMmC+upMVA1KHrT9lhhgJMm4OG/z2vSreH3O+z8="
    - secure: "PSXDjk1GdkkI4Us5WG47Ha3UyGOJ7EtaXncjOTt/R5ujqho8/BcJldorzYokHegX4kXjZpXubNgUvmI/rdbOUK6yTUlE6VG5JIZfcakYtflWL8yeCKocIFCO7PaOxCF70QbH5prx9yW5GK1ofPvXlgsNT2WyoVFFIJFQ72rtlP0="
    - secure: "ClNuKzcxueMmTH9hyPGnOXLPRRrVVHvCmTIYV1BJXTM6UT/G9zSazpCRGaIvlqBEQi+XeBAF1nt2nmNgRZytXEGTZqmrcT1vaHKmH3fRv3Q+Gir4jIC6XAcia9eZcoO6qMnLub/E6GEpd4tTJ23+5amogkArSsPQxEDKzSMZPyk="
    - secure: "AgZ7czAvGk0c5jSJ9/9bc9mNDkcRzEu4Qx+cHpn7m120vVX9/vUG5X+uS7jwyEJNJ6mMLLUzYvoLkpn9b1frw0CiXrOjlrjUmCGPvNfGlDBYk1SCRF8jNh3OzTSH51O/x3qQWYN4le9f2bUdHVrlr9bPZEKBnvpCoHuCw7aQDd8="
    - secure: "NFWAogF6n95aq6HcTiU+0BmLPjs55SU3YFCA8j6aNFmlfjWxrLYPMcj1CR4dqxH6K0nV5Oca+UHlsbxn/btYykU3NZNatcezbTwLCb7uqKUpNYqZCkm21aObxWfotN1E5rrCmIabNFga4Ka6bFTj9YcrkpN6wYpYfiCJwKTCwvU="
    - secure: "RLh+M1mJi9vlzyMnz486PiDpfFmmN5Eiaoweke8xeyyoInZxswpTjOySCkQUhqC8o+jMiA+eLaoPi5fwg0pX1IJob4W8GcAUsSd83/t++W4tjitHq1YIAFMoyRX9+rt5OoFNNMBYrPexw8np2Y82Yvc1iyqRt99NJXI5zi7Yyvo="
    - secure: "fhLEYEVUJc+sRwNOmzgEwp+Thg1olUV69PMD8QZKKKVCmw3It3V8ggaXPCDCta2kc4xuUxws0UenCiLjx05CTrX48Xf8kSLGm2qi8pAERV45XFYEQYNtXaHYOOMqoVSJQw0XMlce87shHoa9s72zH0DlGgLreIfuF/9oSErq0pw="
    - secure: "FOk7axSbunNv/EzLM/9N9kInvBlhSQtYJS6W+TiODdR+PKj+uEHzz82dUdvq/A+PtqFQisHOxtjgkFGjQaN8hop9P/bRUO5Z2zPocmjo3CrvR4gvsjU6qMY5fRntzbfyaj2jH8vPOlskSWn8pmWsYzKjSUDwLg5SIkaTHErS/K4="
    - secure: "CsQ+AkvhGA3IaZlT1hvoenJaNaiA9k6F/5GMIuheWD+G8EeqUrWC6HAy0i+FfipDKz+5mh4pjfqM63lAP1qB0afY8WP/Yh766vEbjQ5AOaKA/ylz/RgdfiQ7g02D+pQLoSf1K98OyjujA7fnSpsT7X0qNItApsLMYDIm654jfjU="
    - secure: "QWfAOx+/bMxhNPDWsNQRDnGa1SQg08x+rCRwd7YR9y7CDqqMYSbaApXBMOZuswbyneYjR8zJCiTNiQt/jqOWwTZy3JFjD9xcEUmlxp7f0uLsU6HrZ4k65dt1XwtArvOrLHGYZQMD4UapRD6wiPU5IwDtxcWJJj8TYEa585nxIZI="
    - secure: "i417LFrqIVR8Pk9iEBkqwUyhb/5Lnjiw5/rN2pnZxmN3KEhOV/IL7EMOUDvL+2qhR/f4sgQgbPqss6oVR8CEAjDUfa87f/o6AOR4Dc54CCOPvfSaoorEoveaAwGU2c0ZwGSe3h6O2HL8XZkRecs2GN8vVvE0Wp57lOD+jjAbmvk="
    - secure: "eWyE9VL9CRBRVdgypVlK/XFpOadPg3eNJ+3bR1URb04MOCG8KI9FbKAVtSip/eB58FsPQp1dU5B/kUmEc3LVDN6B3v5s1OCtA5jqAmxfTYaHHv9ZApbxYVZJ2IKN9xxYPQXEA9v+KHLU6CXLNI3fWNRSKvUkbavusBuFfJRgVvk="
    - secure: "Xkw5lHcxPG6Scb2CF0RSG9J5jJbiwsehLzPIJrvpcdF6Bha61K4yByOw8/A90iX545OVxJugRzKtHP+60FGIijC1qOlWahUnDCFsRKIbtMArkcAZYGyeAIa+IVGdvU0PTNhRYhoVAUVmhODvCzJc++4lkUd+Ciq2VAN/Pk+DL84="
    - secure: "bpF7av+LBXbX0H+xBhWngPXWmrwVl7UraiBJDemnS4Dioz+Q2DYYsJU8SKTJn5G6+3fzLd78HgEgr+e0C2FFRaBx6Ety0mad360CN90OlC/ZXBaHi7i+MJvNfkVkHfyB63S4KxHC2cnE/pmv0wCJ/8uHucL/uvpiCNt/5B8J2Tg="
    - secure: "cAEzZTnOXEIGu88/RaRjbGUammRsyv5LQIAKahZl71ewxTzH6U5BN8TVLQEJmvkjCPoFihW6lzKP+x8vepGkIV4t+aLmhpFUCZYGm5dCWiR2gAjAzxzqa30PAFoqqq9kT/c6W0Bn83vcgos7e+PpTjfcGtI6Rqw0q8Gciv4ul8Q="
    - secure: "fnWCkqYiVPPBlbmREGxqvZfPCyghp3Xy8bAOrYoDCAbFeCg/FTPGgODNUBt0GaQQlGm+dxNPgg+TJpK5s/0LPDefxKSWuYJhULR7KOKxshkEBdpQsTzRkk/2GDgMoHenuBUk2Qx9N/eyZJCdPZejaQ+Qzi3y71o6z5mHV9ZGJfA="
    - secure: "AhtnzmduiI4G66WCPVkElE1T7XjQwPubej8svMdSPz795DFmjBV9j1/0VGQBq7pnETqvpuqb5I6zUe46ZcKOwd2Ahgpr+/vxeVp+3SCea1Dueh9cLRYDWQizkJiMkqlc2q57lzu0b9pLWWeeTPhb6aC/3cFuaoxd9Hiel1P97bE="
    - secure: "Bqpn7kayGJvH94eej0zvq69weyvuSG4lvwSRqSlvoZAksBcGcFJ6ft4aGUsd8cWDhliRyVbZag/EbcfEwgs9t7W/97zlhnOHTjtm83EcAP5YOuZtG1tGrOWCxfC3kqqaD2caTN2WynL0A1GRog2YYsAAflhrWlTHcs6O7UfBWWU="
    - secure: "XRwikHzb3yBfAfgvFQ5RqzVH88lJeD1GopN1tW2eKDYsvauMghhMGbpDmWl95vE7tUBFlD5knXeEYMoIEOTL6DF5qDUF1QyZV7cGLmzMccMUlgNsT6iMt2OOHCBMfalJMFdARut8p9dJd1Vi4P3Qzdu9y/8PXIANXUf4n0AG5hE="
    - secure: "i1gO0RZHnCE2lAmHOK8ozlIKviwaAQVu/NVgycvIboXz4FaMGbleZt6gamyT5Mg4dD8wR9NszA3vWyUlhqCfYLpYIMpMRUP1CP6FfhhR7kMVsjphP+kZroPw9ACY8dyoESIaqflM0+usQFVxajoinqRVZP/LE/7tH6rn3x7+zc0="
    - secure: "fUljUsEgqzxVVg9pu6Wy3RB6/mmox9I5u6biH2HhteaKXkDMeCJDRdrWFPtHkjFEiT5XOzesorSDcXUVp257DUeGAN+EeQ5bsReQXprS45Jrde02Fla0Erplp2YsiNZdgKG9emGGRkYpNth6ZyuwXB3kNJ/s3w6adMsH0Nr6SHA="
before_install:
  # Mono Framework
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  # Bitrock Install Builder
  - wget "http://installbuilder.bitrock.com/installbuilder-enterprise-8.6.0-osx-installer.dmg"
  - hdiutil mount installbuilder-enterprise-8.6.0-osx-installer.dmg
  - sudo '/Volumes/InstallBuilder Multiplatform Enterprise 8.6.0/installbuilder-enterprise-8.6.0-osx-installer.app/Contents/MacOS/installbuilder.sh' --mode unattended --unattendedmodeui none
before_script:
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - cd build-tools
  - ./go.sh travis Release
after_success:
  # Commit the new installers
  - cd .. && mkdir tmp-github.io && cd $_
  - git clone -b master $REPO
  - cd flickr-downloadr.github.io
  - git config push.default tracking
  - git checkout -b deploy-v${BUILDNUMBER}
  - cp -r ../../dist/* ./installer
  - cp ../../build-tools/build.number .
  - git add -f .
  - git commit -m "created release v${BUILDNUMBER}"
  - git push -u origin deploy-v${BUILDNUMBER}
