#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  install_builder_license_signature:
    secure: 3j/EJAZzA8i/OfWyhmvLnzk7SZ8/KNaaTVfWyw0uVhe5gcZfhlGVPfgwrdnvEut3
  GH_TOKEN:
    secure: 2Zfpumy5On2K7O7FtazjQuXNItVtOSktY0qDp2vxR25AaqPy49cvlsaueX+tuWR/
  FD_CERT_PWD:
    secure: LDV1CBXqfvvW0VpFmQX6Zbp7Eik6IJ4TxdDwaKgpTC+A9DAX/H2GRssOmqB+BWZj

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build-tools
  - go appveyor Release
  - echo 'Build (and Deploy) completed...'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: dist
    name: dist
    type: zip

  - path: build-tools\*.log
    name: logs
    type: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#
#---------------------------------#
#   open RDP on the build agent   #
#---------------------------------#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
