#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  repo: "https://github.com/flickr-downloadr/flickr-downloadr.github.io.git"
  oauth_token:
    secure: lYR11R1tdRsM90UhyXCxCUf30lhL/OJ40Sb9pPzc4mFRSVhVRZw449MqLf+phNRT
  install_builder_license_signature:
    secure: 3j/EJAZzA8i/OfWyhmvLnzk7SZ8/KNaaTVfWyw0uVhe5gcZfhlGVPfgwrdnvEut3
  gh_token:
    secure: Nww9ToyuLy9Dam9uQ/gp60uD2fMNrdVyZ9zzAfgtOubVCItC2xcWMtvwaZQ8bRDF

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build-tools
  - go appveyor Release
  - echo 'Build (and Deploy) completed...'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: dist
    name: dist
    type: zip

  - path: build-tools\*.log
    name: logs
    type: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:
- git config --global user.name "The CI Bot"
- git config --global user.email "contact.us@flickrdownloadr.com"
- set /p buildNumber= <build.number
- set version=v%buildNumber%
- set deployVersion=deploy-%version%
- cd ..\..
- git clone -b master %REPO%
- cd flickr-downloadr.github.io
- git config credential.helper "store --file=.git\fd-credentials"
- echo "https://%GH_TOKEN%:@github.com" > .git\fd-credentials
- git config push.default tracking
- git checkout -b %deployVersion%
- xcopy /E ..\flickr-downloadr-gtk\dist installer
- git add -f .
- git commit -m "created release %version% (appveyor) [ci skip]" -s
- git ls-remote --heads origin | findstr %deployVersion% && git pull --rebase origin %deployVersion% || ver > nul
- git ls-remote --heads origin | findstr %deployVersion% && git push origin %deployVersion% || git push -u origin %deployVersion%
