#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  install_builder_license_signature:
    secure: 3j/EJAZzA8i/OfWyhmvLnzk7SZ8/KNaaTVfWyw0uVhe5gcZfhlGVPfgwrdnvEut3
  gh_token:
    secure: K8R2b8g3A8zB4IFQ0/G/fU8IKhU3PoFaKZARKl0IbCUvVxfzzfVY9yKUVPjM4M4V
  FD_CERT_PWD:
    secure: L/AukSGIeEiIO4UrrwH+6RKBgPMqdHKAWQU1h++JlcI=
  FD_CERT_URL:
    secure: HsUlRYdK4uz7P1KFzPEWFcteY7kF5MzTwbzvPBu0hCze7Dv9BzMjnejGXg3tDvBJaZfXhhwhJItQCVMJSHuUL2hfG+u4UQR0xFJaoWhCr7M=

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build-tools
  - go appveyor Release
  - echo 'Build (and Deploy) completed...'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: dist
    name: dist
    type: zip

  - path: build-tools\*.log
    name: logs
    type: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#
