#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  install_builder_license_signature:
    secure: 3j/EJAZzA8i/OfWyhmvLnzk7SZ8/KNaaTVfWyw0uVhe5gcZfhlGVPfgwrdnvEut3
  gh_token:
    secure: g24l+LoZgp3MgeD26FPYtnRIhSXqx9yIzRoWyVbRJ5vcYekx2yB85Qjd0UfflIgv
  FD_CERT_PWD:
    secure: LDV1CBXqfvvW0VpFmQX6Zbp7Eik6IJ4TxdDwaKgpTC+A9DAX/H2GRssOmqB+BWZj
  FLICKR_DOWNLOADR_SHARED_SECRET:
    secure: D4KY6IRkAEYkUFG6nOXm2fKkOPQL4xMXrskcqCB9pK83bBaDLuag43izJS+6mhOUkFMxfNrRPb2/IC7Doo1+dQ==
  FLICKR_DOWNLOADR_CONSUMER_KEY:
    secure: kYO9cheSs9qFdw/DXr1Ny2ej6kT/1iwEYbgHu8sCeAbrPzWpqcWoI6umUcbgK21y36z9/SZZXwPhyKt/tT2Ik4oVO4b3YhB6Ssil/oQDNL26+4AfOqYWUNfD8wTs9T/M
  FLICKR_DOWNLOADR_CONSUMER_SECRET:
    secure: zf/Wl0Go3HEPHqH8X/x0plLnHPm3rjcxklMZBeLGLcTr9yGy1eiAoUaTVStE79P4JJC/0JM+i/N5zrp/jT4R+VxOpjV0JTqvAxWwDkCCbtU=

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build-tools
  - go appveyor Release
  - echo 'Build (and Deploy) completed...'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: dist
    name: dist
    type: zip

  - path: build-tools\*.log
    name: logs
    type: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
